name: Deploy to GitHub Container Registry

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to GitHub Container Registry
      uses: docker/build-push-action@v1
      with:
        name: theteamaker/shirim
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: ghcr.io
        repository: theteamaker/shirim
        tags: latest